# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 15:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0004_neighborhoodpage_newbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhoodpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='neighborhoodpage',
            name='newbody',
        ),
        migrations.AddField(
            model_name='neighborhoodpage',
            name='mainContent',
            field=wagtail.wagtailcore.fields.StreamField([('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('link', wagtail.wagtailcore.blocks.URLBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())], default=''),
            preserve_default=False,
        ),
    ]
