# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0005_auto_20160811_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhoodpage',
            old_name='mainContent',
            new_name='main_content',
        ),
    ]
