# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0007_neighborhoodpage_draw_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhoodpage',
            name='neighborhood',
        ),
        migrations.DeleteModel(
            name='neighborhoodCHI',
        ),
    ]
