# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('neighborhoods', '0009_auto_20160904_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicagoneighborhoods',
            name='introductory_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='chicagoneighborhoods',
            name='introductory_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='urbandesign',
            name='introductory_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='urbandesign',
            name='introductory_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
