# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 16:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0011_auto_20160905_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicagoneighborhoods',
            name='draw_neighborhood',
            field=wagtail.wagtailcore.fields.StreamField([('draw', wagtail.wagtailcore.blocks.StructBlock([(b'drawnNeighborhood', wagtail.wagtailcore.blocks.TextBlock())]))]),
        ),
        migrations.AlterField(
            model_name='urbandesign',
            name='draw_neighborhood',
            field=wagtail.wagtailcore.fields.StreamField([('draw', wagtail.wagtailcore.blocks.StructBlock([(b'drawnNeighborhood', wagtail.wagtailcore.blocks.TextBlock())]))]),
        ),
    ]
