# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0012_auto_20160905_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicagoneighborhoods',
            name='neighborhood_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
