# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0014_auto_20161004_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicagoneighborhoods',
            name='draw_neighborhood',
            field=wagtail.wagtailcore.fields.StreamField([('draw', wagtail.wagtailcore.blocks.StructBlock([(b'drawnNeighborhood', wagtail.wagtailcore.blocks.TextBlock())])), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]),
        ),
    ]
