# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 23:31
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0015_auto_20161011_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urbandesign',
            name='sketches',
        ),
        migrations.AlterField(
            model_name='chicagoneighborhoods',
            name='amenities',
            field=wagtail.wagtailcore.fields.StreamField([('draw', wagtail.wagtailcore.blocks.StructBlock([(b'drawnNeighborhood', wagtail.wagtailcore.blocks.TextBlock())])), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]),
        ),
        migrations.AlterField(
            model_name='chicagoneighborhoods',
            name='connections',
            field=wagtail.wagtailcore.fields.StreamField([('draw', wagtail.wagtailcore.blocks.StructBlock([(b'drawnNeighborhood', wagtail.wagtailcore.blocks.TextBlock())])), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]),
        ),
        migrations.AlterField(
            model_name='chicagoneighborhoods',
            name='public_space',
            field=wagtail.wagtailcore.fields.StreamField([('draw', wagtail.wagtailcore.blocks.StructBlock([(b'drawnNeighborhood', wagtail.wagtailcore.blocks.TextBlock())])), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]),
        ),
        migrations.AlterField(
            model_name='chicagoneighborhoods',
            name='social_mix',
            field=wagtail.wagtailcore.fields.StreamField([('draw', wagtail.wagtailcore.blocks.StructBlock([(b'drawnNeighborhood', wagtail.wagtailcore.blocks.TextBlock())])), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())]),
        ),
    ]
