# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-12 16:29
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0019_remove_chicagoneighborhoods_draw_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicagoneighborhoods',
            name='overview',
            field=wagtail.wagtailcore.fields.StreamField([('draw', wagtail.wagtailcore.blocks.StructBlock([(b'drawnNeighborhood', wagtail.wagtailcore.blocks.TextBlock())])), ('heading', wagtail.wagtailcore.blocks.CharBlock(classname='heading')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('video', wagtail.wagtailembeds.blocks.EmbedBlock()), ('document', wagtail.wagtaildocs.blocks.DocumentChooserBlock())], default=''),
        ),
    ]
